<a href="https://colab.research.google.com/github/KhushalMitbaokar/DataScience/blob/main/heart_desease_prediction_with_multiple_sample_cases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

import cufflinks as cf

import os
from sklearn.metrics import accuracy_score,mean_squared_error
import plotly.offline as pyo
from plotly.offline import init_notebook_mode,plot,iplot

In [ ]:
pyo.init_notebook_mode(connected=True)
cf.go_offline()

In [ ]:
heart=pd.read_csv('heart.csv')

In [ ]:
heart

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
info = ["age","1: male, 0: female","chest pain type, 1: typical angina, 2: atypical angina, 3: non-anginal pain, 4: asymptomatic","resting blood pressure"," serum cholestoral in mg/dl","fasting blood sugar > 120 mg/dl","resting electrocardiographic results (values 0,1,2)"," maximum heart rate achieved","exercise induced angina","oldpeak = ST depression induced by exercise relative to rest","the slope of the peak exercise ST segment","number of major vessels (0-3) colored by flourosopy","thal: 3 = normal; 6 = fixed defect; 7 = reversable defect"]



for i in range(len(info)):
    print(heart.columns[i]+":\t\t\t"+info[i])

age:			age
sex:			1: male, 0: female
cp:			chest pain type, 1: typical angina, 2: atypical angina, 3: non-anginal pain, 4: asymptomatic
trestbps:			resting blood pressure
chol:			 serum cholestoral in mg/dl
fbs:			fasting blood sugar > 120 mg/dl
restecg:			resting electrocardiographic results (values 0,1,2)
thalach:			 maximum heart rate achieved
exang:			exercise induced angina
oldpeak:			oldpeak = ST depression induced by exercise relative to rest
slope:			the slope of the peak exercise ST segment
ca:			number of major vessels (0-3) colored by flourosopy
thal:			thal: 3 = normal; 6 = fixed defect; 7 = reversable defect


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X,y=heart,heart.target

In [ ]:
sc = StandardScaler()
X = sc.fit_transform(X)

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=10,test_size=0.3,shuffle=True)

In [ ]:
X_test

array([[ 0.18017482, -1.46841752, -0.93851463, ...,  1.24459328,
         1.12302895, -1.09345881],
       [ 0.40075247,  0.68100522,  1.00257707, ...,  0.26508221,
         1.12302895, -1.09345881],
       [ 1.06248543,  0.68100522,  1.00257707, ..., -0.71442887,
         1.12302895, -1.09345881],
       ...,
       [ 0.29046364,  0.68100522,  1.00257707, ...,  0.26508221,
         1.12302895, -1.09345881],
       [-0.26098049,  0.68100522,  0.03203122, ..., -0.71442887,
        -0.51292188,  0.91452919],
       [ 0.62133012,  0.68100522, -0.93851463, ...,  1.24459328,
         1.12302895, -1.09345881]])

In [ ]:
y_test

246    0
183    0
229    0
126    1
184    0
      ..
69     1
21     1
210    0
78     1
174    0
Name: target, Length: 91, dtype: int64

In [ ]:
scores_dict = {}
Catagory=['No....but i pray you get Heart Disease or at leaset Corona Virus Soon...','Yes you have Heart Disease....RIP in Advance']

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
prediction=dt.predict(X_test)
accuracy_dt=accuracy_score(y_test,prediction)*100
print(accuracy_dt)

100.0


In [ ]:
X_test[1]

array([ 0.40075247,  0.68100522,  1.00257707, -1.12077005, -0.31431015,
       -0.41763453, -1.00583187,  0.67140036, -0.69663055,  1.25987717,
       -0.64911323,  0.26508221,  1.12302895, -1.09345881])

In [ ]:
print("Accuracy on training set: {:.3f}".format(dt.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(dt.score(X_test, y_test)))

Accuracy on training set: 1.000
Accuracy on test set: 1.000


In [ ]:
prediction

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0])

In [ ]:
#sample prediction

In [ ]:
q=np.zeros(14)
p=np.zeros(14)
u=np.zeros(14)
q[0] = 60   
q[1] = 0
q[2] = 3     
q[3] = 140   
q[4] = 241   
q[5] = 0     
q[6] = 1
q[7] = 123
q[8] = 1
q[9] = 0.2
q[10] = 1
q[11] = 0
q[12] = 3
q[13] = 0

p[0] = 57    
p[1] = 0
p[2] = 3     
p[3] = 140   
p[4] = 241   
p[5] = 0     
p[6] = 1
p[7] = 123
p[8] = 1
p[9] = 0.2
p[10] = 1
p[11] = 0
p[12] = 3
p[13] = 0

u[0] = 57    
u[1] = 0
u[2] = 3     
u[3] = 140   
u[4] = 241   
u[5] = 0     
u[6] = 1
u[7] = 123
u[8] = 1
u[9] = 0.2
u[10] = 1
u[11] = 0
u[12] = 3
u[13] = 0
v=np.zeros(14)
v[:]=[57,0,3,140,241,0,1,123,1,0.2,1,0,3,0]
temp=dt.predict([q,p,v,u])
print(temp)

[1 1 1 1]


In [ ]:
for i in temp:
  print(Catagory[i])

Yes you have Heart Disease....RIP in Advance
Yes you have Heart Disease....RIP in Advance
Yes you have Heart Disease....RIP in Advance
Yes you have Heart Disease....RIP in Advance
